[wordpress]
#18.215.184.140 #wordpress-1-az-b
#44.199.253.110 #wordpress-2-az-b
100.24.49.246

[all:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=/Users/TallesGois/.ssh/wordpress-turbinado-key